### ISSUE TITLE
Unable to extract uploader id

### ISSUE THREAD

**Issue by chloehuang123** [ninjakx/youtube-video2ppt#5] opened 2023-02-18 21:14 UTC
I'm running into this error message: 
<img width="491" alt="Screen Shot 2023-02-18 at 4 11 57 PM" src="https://user-images.githubusercontent.com/72413057/219899680-4d37b0ae-5421-4b73-a5f5-ae077a058d40.png">
I'm seeing some people report the same error here: https://github.com/yt-dlp/yt-dlp/issues/6247#issuecomment-1433096554 and a person fixed it: 
<img width="742" alt="Screen Shot 2023-02-18 at 4 12 54 PM" src="https://user-images.githubusercontent.com/72413057/219899716-a85925b8-8be7-4cfb-b641-652a907802b2.png">
Idk which file for this repo should be edited in order to solve the problem, anyone has a clue?

**Comment by ninjakx** [comment] 2023-02-19 13:56
@chloehuang123 yes this problem is there since Thursday night. This Friday I also had the same issue and changing regex on `yt_dlp` didn't help me. As when I traced the issue I found it was calling `youtube_dl` from anaconda and after replacing the regex with the above photo one it worked.

**Comment by ninjakx** [comment] 2023-02-19 13:59
https://github.com/ytdl-org/youtube-dl/issues/31530#issuecomment-1433470254

Change has to be made on `youtube_dl` not `yt_dlp`
As the script call from `youtube_dl` repo.

**Comment by chloehuang123** [comment] 2023-02-19 16:26
@ninjakx I changed this line according to the link you mentioned above: 
<img width="797" alt="Screen Shot 2023-02-19 at 11 21 52 AM" src="https://user-images.githubusercontent.com/72413057/219961017-d7c323e6-7138-4951-90b5-c2383aa44a68.png">

but now I'm getting this error:
<img width="485" alt="Screen Shot 2023-02-19 at 11 26 35 AM" src="https://user-images.githubusercontent.com/72413057/219961039-facb5554-9654-439c-8a35-617441a2f2eb.png">

Any idea?

**Comment by ninjakx** [comment] 2023-02-19 18:00
Try with 
https://www.youtube.com/watch?v=LsK-xG1cLYA

Without url shortner

**Comment by ninjakx** [comment] 2023-02-19 18:07
Try adding `--rm-cache-dir` to 
`youtube-dl --rm-cache-dir` command in https://github.com/ninjakx/youtube-video2ppt/blob/1faa3e44e3b189556085d930bf4d722edc0c291c/vid2ppt.sh#L98

Source: https://stackoverflow.com/questions/32104702/youtube-dl-library-and-error-403-forbidden-when-using-generated-direct-link-by

https://github.com/ytdl-org/youtube-dl/issues/6451#issuecomment-128445036

Have not tested it as I am currently using my phone.
If it does not work I will try to look into it tomorrow :)

**Comment by chloehuang123** [comment] 2023-02-19 19:23
@ninjakx Thanks for the response! It still doesn't work for me though: 

<img width="1168" alt="Screen Shot 2023-02-19 at 2 23 06 PM" src="https://user-images.githubusercontent.com/72413057/219970449-65ce6645-393d-4c51-a160-f8e3fdddd176.png">

**Comment by ninjakx** [comment] 2023-02-20 03:51
The error is due to zenity. You have not installed zenity which is used to see the downloading of video progress. I recently updated my script and added zenity to it. 
Zenity works on ubuntu, not on window.

Here is the installation command:
```
sudo apt-get update
sudo apt-get install zenity
```
I guess I need to update the readme as well.

Hope you don't get any issue after that.

**Comment by ninjakx** [comment] 2023-02-20 04:03
```
| grep --line-buffered -oP '^\[download\].*?\K([0-9.]+\%|#\d+ of \d)' |
    zenity --progress \
    --width=400 \
  --title="Downloading youtube video" \
  --text="Downloading..." \
  --percentage=0
```

The problem is coming from this added line in bash file.

**Comment by CeliaBlorville** [comment] 2023-02-20 14:23
Hi everyone, I am facing the same issue. I modified the indicated line but now i get this error : 

File "/usr/local/lib/python3.6/dist-packages/pafy/pafy.py", line 52, in <module>
"pafy: youtube-dl not found; you can use the internal backend by "
ImportError: pafy: youtube-dl not found; you can use the internal backend by setting the environmental variable PAFY_BACKEND to "internal". It is not enabled by default because it is not as well maintained as the youtube-dl backend.

Is there someone who can help me ? :)

**Comment by ninjakx** [comment] 2023-02-20 14:45
@CeliaBlorville Hi celia can you try with the recent changes I have made? and let me know if there is any issue running the script. I have merged the PR which fixes the `yt_dlp` issue so currently not using `youtube-dl`

**Comment by CeliaBlorville** [comment] 2023-02-20 15:27
Thank's @ninjakx for your rapid answer, I'm trying it !

**Comment by chloehuang123** [comment] 2023-02-20 16:31
@ninjakx Thanks for the quick response! I cloned the updated repo again and followed the instruction, and I'm seeing this: 
<img width="1168" alt="Screen Shot 2023-02-20 at 11 28 58 AM" src="https://user-images.githubusercontent.com/72413057/220159272-be6ecbcf-e49a-46ba-8c5c-1394d9259e84.png">

Is it because Zenity is not working on MacOS? should I download virtualization software, run Ubuntu, and then use the repo again?

**Comment by ninjakx** [comment] 2023-02-20 17:53
@chloehuang123 for mac: `brew install zenity` install via brew. If you don't want to see the progress for downloading video just remove that line from bash script as I have mentioned before. But I think after installing the zenity you should not be getting any more error. Btw I checked the link you want to create ppt for and I fixed all the error that occured while passing that given url link so I think after this installation part (zenity) everything will be fine. If not let me know.

**Comment by chloehuang123** [comment] 2023-02-20 19:30
@ninjakx Thanks for looking into the issue! I installed zenity successfully but I'm getting the same error after running the bash command: 
<img width="1135" alt="Screen Shot 2023-02-20 at 2 29 44 PM" src="https://user-images.githubusercontent.com/72413057/220185815-7b8c5e4a-39cf-4357-a17c-678e14fea01e.png">

Any idea?

**Comment by ninjakx** [comment] 2023-02-21 03:52
Can you post the traceback as a text and also check your directory '5' what files it is containing? Is it empty?
Have to check for the broken pipe thing.

Were you using Mac OS before this script was working for you?
Is this occuring now onwards?

Can you try with some small videos like 5-6 min video?
This error occurs usually if your request is blocked or takes too long and give you request side timeout.

**Comment by chloehuang123** [comment] 2023-02-21 15:22
Hi @ninjakx, thanks for your reply! I tried a 6 mins long video and I'm getting the same error message: 

ERROR: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/Users/chloe/opt/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1502, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/chloe/opt/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 1578, in __extract_info
    ie_result = ie.extract(url)
  File "/Users/chloe/opt/anaconda3/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 691, in extract
    self.to_screen('Extracting URL: %s' % (
  File "/Users/chloe/opt/anaconda3/lib/python3.9/site-packages/yt_dlp/extractor/common.py", line 1114, in to_screen
    self._downloader.to_screen(f'[{self.IE_NAME}] {msg}', *args, **kwargs)
  File "/Users/chloe/opt/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 872, in to_screen
    self._write_string(
  File "/Users/chloe/opt/anaconda3/lib/python3.9/site-packages/yt_dlp/YoutubeDL.py", line 853, in _write_string
    write_string(message, out=out, encoding=self.params.get('encoding'))
  File "/Users/chloe/opt/anaconda3/lib/python3.9/site-packages/yt_dlp/utils.py", line 2049, in write_string
    out.flush()
BrokenPipeError: [Errno 32] Broken pipe

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

I had no problem using it on the same Mac OS machine a few weeks ago, and dictory '5' would always be generated for me successfully. But since the "stopIteration" appeared two days ago, this repo stopped working for me.. this "Broken pipe" is showing and I don't see any dictory '5' in the folder..

**Comment by ninjakx** [comment] 2023-02-21 16:18
I ain't able to reproduce in Linux and not able to think of any solution currently. Will recheck again on Linux. If it's related to Mac os, have to check up with the yt-dlp repo owner. 
Since the old script was running 3 days before. May be have to improve that one. 
May be some config might require as earlier u were facing issue related to 403 forbidden. Have to check it.

**Comment by ninjakx** [comment] 2023-02-21 16:38
Also please check your version. Is this same as urs?
`
pip freeze`

```
Brotli==1.0.9
certifi==2020.12.5
lxml==4.6.3
mutagen==1.46.0
numpy==1.19.3
opencv-python==4.5.2.52
Pillow==8.2.0
pycryptodomex==3.17
python-pptx==0.6.19
pytube==10.8.2
websockets==10.4
XlsxWriter==1.4.3
yt-dlp==2023.2.17
```

**Comment by ninjakx** [comment] 2023-02-21 16:45
Does this command works for you: 
```
yt-dlp --force-ipv4 -f 244 --verbose --newline -o "sample_directory/sample_title/title.mp4" "https://youtu.be/vMh0zPT0tLI"
```
after then
remove `--force-ipv4` in the command to see what error it is throwing you.

You are getting the same error for `yt-dlp` & `youtube-dl`. So I guess it could be due to macOS and version issue.
It could be mac version related: https://github.com/ytdl-org/youtube-dl/issues/14044.

**Comment by chloehuang123** [comment] 2023-02-22 14:58
@ninjakx thanks for the reply! the command worked for me and an mp4 video was downloaded in the sample folder!

**Comment by chloehuang123** [comment] 2023-02-22 15:00
But I'm still seeing this broken pipe and stopiteration issue when I try out the repo: 

BrokenPipeError: [Errno 32] Broken pipe

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

Traceback (most recent call last):
  File "/Users/chloe/Desktop/youtube3/youtube-video2ppt/save_yl_slide.py", line 15, in <module>
    vid_path = next(Path(args['path']).glob('*.mp4'))
StopIteration

**Comment by chloehuang123** [comment] 2023-02-22 15:21
@ninjakx Wait.. this is very weird.. the older version of the repo started working.. 
<img width="836" alt="Screen Shot 2023-02-22 at 10 19 55 AM" src="https://user-images.githubusercontent.com/72413057/220667252-e1e169bf-6501-4d76-a47b-a84b891596a2.png">

and the ppt file got generated successfully in the folder!

**Comment by ninjakx** [comment] 2023-02-22 16:03
oh

Use the older(version that working for you) repo just add the `-f 244 --verbose ` in `youtube-dl` because we don't need audio for creating ppt. So getting video is enough and will be faster to download.

**Comment by ninjakx** [comment] 2023-02-22 16:13
When you run the command I gave you it worked for you and mp4 was created. 
1) it works `yt-dlp --force-ipv4 -f 244 --verbose --newline -o "sample_directory/sample_title/title.mp4" "https://youtu.be/vMh0zPT0tLI"`
then this should work too
`python save_yl_slide.py -s 5 -p sample_directory/sample_title`

if it works problem might be related to zenity.

remove the zenity 
these line
```
| grep --line-buffered -oP '^\[download\].*?\K([0-9.]+\%|#\d+ of \d)' |
    zenity --progress \
    --width=400 \
  --title="Downloading youtube video" \
  --text="Downloading..." \
  --percentage=0
```

hope it works :( else I don't know what could be the issue use the older version with the changes I told you (to fasten the downloading process)

**Comment by chloehuang123** [comment] 2023-02-23 14:57
@ninjakx unfortunately, the python command line didn't work for me :( and here's the error message:

 youtube-video2ppt git:(main) ✗ python save_yl_slide.py -s 5 -p sample_directory/sample_title
Traceback (most recent call last):
  File "/Users/chloe/Desktop/youtube/youtube-video2ppt/save_yl_slide.py", line 15, in <module>
    vid_path = next(Path(args['path']).glob('*.mp4'))
StopIteration

**Comment by chloehuang123** [comment] 2023-02-23 14:58
@ninjakx Ohhh it worked!!

**Comment by chloehuang123** [comment] 2023-02-23 15:05
After removing the zenity, it's working now!! Thanks so much @ninjakx! Do you want me to close the issue here?

**Comment by ninjakx** [comment] 2023-02-24 07:37
Yes you can close the issue if it is resolved :)

**Closed as completed** 2023-02-24 21:19 UTC
